<?php
/**
 * Advertise
 * Catalog product related items block
 *
 * @category    Advertise
 * @package     Advertise_RelatedProducts
 */

class Advertise_RelatedProducts_Block_Related extends Mage_Catalog_Block_Product_List_Related
{
    /**
     * Default MAP renderer type
     *
     * @var string
     */
    protected $_mapRenderer = 'msrp_noform';

    protected $_itemCollection;

    protected function _prepareData() {
        // Get product
        //$product = Mage::registry('product');
        $prodid = $this->getRequest()->getParam('id');
        $product = Mage::getModel('catalog/product')->load($prodid);

        // Get related product IDs from request
        $ids = $this->getRequest()->getParam('ids');
        if (!$ids) {
            $ids = array();
        }
        array_push($ids, '0');

        // Get count of related products required
        $relatedCount = Mage::getStoreConfig('advertise_suggestedproducts_options/advertise_suggested_products/advertise_related_prod_count');

        // Get collection of products
        $relateds = Mage::getResourceModel('catalog/product_collection');

        // Select which fields to load into the product
        // * will load all fields but it is possible to pass an array of select fields to load
        $relateds->addAttributeToSelect('*');

        // Add list of IDs to select
        $i = 0;
        $conditions = array();
        foreach ($ids as $id) {
            if ($i < $relatedCount) {
                array_push($conditions, array('attribute' => 'entity_id', 'eq' => $id));
            } else {
                // Have enough related products
                break;
            }
            $i++;
        }
        $relateds->addAttributeToFilter($conditions);

        // Ensure the product is enabled
        $relateds->addAttributeToFilter('status', 1);

        // For DEBUG: Print out the SQL query generated by the collection object so far
        // Mage::log('SELECT QUERY: ' . $relateds->getSelect());

        // Load the collection
        $relateds->load();

        $this->_itemCollection = new Varien_Data_Collection();
        foreach ($relateds as $item) {
            $this->_itemCollection->addItem($item);
        }

        // If we've got enough related products then we're done.
        if (count($this->_itemCollection) == $relatedCount) {
            foreach ($this->_itemCollection as $product) {
                $product->setDoNotUseCategoryId(true);
            }
            return $this;
        }

        // Not enough related products yet so look in Magento DB to see if any are set for product.
        // This section based on base Magento code
        $relateds2 = $product->getRelatedProductCollection()
                    ->addAttributeToSelect('required_options')
                    ->setPositionOrder()
                    ->addStoreFilter()
        ;
        if (Mage::helper('catalog')->isModuleEnabled('Mage_Checkout')) {
            Mage::getResourceSingleton('checkout/cart')->addExcludeProductFilter($relateds2,
                    Mage::getSingleton('checkout/session')->getQuoteId()
            );
            $this->_addProductAttributesAndPrices($relateds2);
        }
        Mage::getSingleton('catalog/product_visibility')->addVisibleInCatalogFilterToCollection($relateds2);
        $relateds2->load();

        // Add items from DB to related products
        foreach ($relateds2 as $item) {
            $this->_itemCollection->addItem($item);
            // If we've got enough related products then we're done.
            if (count($this->_itemCollection) == $relatedCount) {
                foreach ($this->_itemCollection as $product) {
                    $product->setDoNotUseCategoryId(true);
                }
                return $this;
            }
        }

        // Still haven't got the required number of related products so fill up with random products
        $numRandomsToGet = $relatedCount - count($this->_itemCollection);

        // Get a list of 100 random product IDs
        // (To execute SQL query directly: 1. Get the resource model, 2. Retrieve the read connection, 3. Execute the query)
        $resource = Mage::getSingleton('core/resource');
        $readConnection = $resource->getConnection('core_read');
        $query = 'SELECT MAX(entity_id) AS maxid FROM ' . $resource->getTableName('catalog/product');
        $maxid = $readConnection->fetchOne($query);
        if (!$maxid) {
            $maxid = $prodid;
        }
        $randids = array();
        for ($i = 0; $i <= 100; $i++) {
            array_push($randids , rand(1,$maxid));
        }

        // Select random products
        // DO NOT USE $randCollection->getSelect()->order('rand()');
        // AS VERY INEFFICIENT; TOO LONG FOR LARGE PRODUCT COLLECTIONS
        $randCollection = Mage::getResourceModel('catalog/product_collection');
        Mage::getModel('catalog/layer')->prepareProductCollection($randCollection);
        // Select from the 100 random IDs
        $randCollection->addIdFilter($randids, false);
        $randCollection->addStoreFilter();
        $randCollection->getSelect()->limit($numRandomsToGet);
        //$randCollection->setPage(1, $numRandomsToGet);

        // Don't get items we already have
        $exclude = $this->_itemCollection->getAllIds();
        $toexclude = array();
        foreach($exclude as $ex) {
            $toexclude[] = $ex;
        }
        // Don't include the current item as a related product
        $id = $this->getRequest()->getParam('id');
        if ($id) {
            $toexclude[] = $id;
        }
        // Don't include basket items as related products
        $session = Mage::getSingleton('checkout/session');
        foreach ($session->getQuote()->getAllVisibleItems() as $item) {
            $toexclude[] = $item->getProductId();
        }
        $randCollection->addIdFilter($toexclude, true);
        // Mage::log('RANDOM RELATED ITEM SELECT QUERY:' . $randCollection->getSelect());
        foreach($randCollection as $randProduct)
        {
            $this->_itemCollection->addItem($randProduct);
        }

        foreach ($this->_itemCollection as $product) {
            $product->setDoNotUseCategoryId(true);
        }
        return $this;

    }

    protected function _beforeToHtml()
    {
        $this->_prepareData();
        return parent::_beforeToHtml();
    }

    public function getItems()
    {
        $this->_itemCollection->setPageSize(count($this->_itemCollection));
        return $this->_itemCollection;
    }
}
